services:
  ollama:
    build:
      context: .
      dockerfile: ollama.Dockerfile
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:11434"]
      interval: 10s
      timeout: 5s
      retries: 10

  mash_backend:
    build:
      context: ./MASH_backend
    container_name: mash_backend
    environment:
      - OLLAMA_URL=http://ollama:11434/api/generate
    ports:
      - "8000:8000"
    depends_on:
      ollama:
        condition: service_healthy
    restart: unless-stopped
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    volumes:
      - mash_backend_logs:/logs

  playmash:
    build:
      context: ./playmash
    container_name: playmash
    ports:
      - "5173:5173"
    depends_on:
      - mash_backend
    restart: unless-stopped

volumes:
  ollama_data:
  mash_backend_logs:
